### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'file_data' in

### ISSUE THREAD

**Issue by rpsjr** [googleapis/nodejs-vertexai#249]
#### Environment details

  - Programming language: TS / JS
  - OS: macOS 14.1.2 (23B92)
  - Language runtime version: node v20.8.0
  - Package version:    "@google-cloud/vertexai",  "version": "0.5.0",

#### Steps to reproduce

`  0.  return model.startChat({history: currentHistory, tools: functionDeclarations, });
  1. const chat = getOrCreateChatSession(chatId);
  2. const streamingResult1 = await chat.sendMessageStream('hard test'); `

 

error:    Unhandled Rejection: TypeError: Cannot use 'in' operator to search for 'file_data' in

    at validateGcsInput /@google-cloud/vertexai/src/functions/pre_fetch_processing.ts:64:22)
    at validateGenerateContentRequest @google-cloud/vertexai/src/functions/pre_fetch_processing.ts:46:3)
    at generateContentStream @google-cloud/vertexai/src/functions/generate_content.ts:113:33)
    at ChatSessionPreview.sendMessageStream @google-cloud/vertexai/src/models/chat_session.ts:350:69)
    at mainGoogle /src/service/google.ts:139:39)
    at <anonymous> src/index.ts:111:29)
    at Timeout._onTimeout src/index.ts:124:15)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

**Comment by rpsjr** [comment]
There was a typo while passing chat history text parts.
