### ISSUE TITLE
Error in response from response on generate content

### ISSUE THREAD

**Issue by xxjt123xx** [googleapis/nodejs-vertexai#252]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - Programming language: node.js
  - OS : cloud function
  - Language runtime version: Node.js 20
  - Package version: 0.5.0

#### Steps to reproduce

  1. use this code : https://www.npmjs.com/package/@google-cloud/vertexai?activeTab=readme#content-generation-non-streaming 
  2. This happens when using this in a cloud function not as an http request/response

Making sure to follow these steps will guarantee the quickest resolution possible.

- Error
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5329:19)
    at successSteps (node:internal/deps/undici/undici:5300:27)
    at fullyReadBody (node:internal/deps/undici/undici:1447:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:5309:7)
    at async throwErrorIfNotOK (/workspace/node_modules/@google-cloud/vertexai/build/src/functions/post_fetch_processing.js:28:27)
    at async generateContent (/workspace/node_modules/@google-cloud/vertexai/build/src/functions/generate_content.js:51:5)
    at async getVertextAIResults (/workspace/index.js:97:16)
    at async addContract (/workspace/index.js:40:19)

Thanks!

**Comment by xxjt123xx** [comment]
this is working today. no code changes. Might have been a service issue.
